---
title: "Optical Density"
output:
  pdf_document: 
    keep_tex: no
    latex_engine: lualatex
    template: ../worksheetTemplate.tex
  html_document: default
subtitle: Refraction
institute: Version a
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pracma)
```

For each of the following ray diagrams identify the more optically dense material.

```{r, results = "asis", echo=FALSE}
## Load the refractive indices (taken from wikipedia)
refractiveIndices <- read.csv("../ReferenceData/RefractiveIndices.csv")

## Base template for creating a refraction ray diagram, originally found here: http://texample.net/tikz/examples/refraction/
template <- "\\scalebox{0.8}{\\begin{tikzpicture}

    %% define coordinates
    \\coordinate (O) at (0,0) ;
    \\coordinate (A) at (0,3) ;
    \\coordinate (B) at (0,-3) ;
    
    %% media
    \\fill[blue!25!,opacity=.3] (-3,0) rectangle (3,3);
    \\fill[blue!60!,opacity=.3] (-3,0) rectangle (3,-3);
    \\node[right,text width=1.9cm] at (0.5,2) {%s};
    \\node[right,text width=1.9cm] at (-2.5,-2) {%s};

    %% rays
    \\draw[red, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{<}}}}] (O) -- (%s:%s);
    \\draw[blue,ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{>}}}}] (O) -- (-%s:%s);

    %% axis
    \\draw[dash pattern=on5pt off3pt] (A) -- (B);

    %% angles
    \\draw (0,1) arc (90:%s:1);
    \\draw (0,-1.4) arc (270:%s:1.4) ;
    \\node[] at (%s:1.4)  {$\\theta_{1}$};
    \\node[] at (%s:1.8)  {$\\theta_{2}$};
\\end{tikzpicture}}"

printstring<-"\\begin{center}\\begin{tabular}{ p{5cm} p{5cm} p{5cm} }"
answers<-array()

## Loop to create each example
for (i in 1:12) {
  materialSamples <-sample(1:nrow(refractiveIndices), 2, replace=T)
  material1name <- sub("%","\\\\%",refractiveIndices$Material[materialSamples[1]])
  material2name <- sub("%","\\\\%",refractiveIndices$Material[materialSamples[2]])
  material1refractiveIndex <-refractiveIndices$RefractiveIndex[materialSamples[1]]
  material2refractiveIndex <-refractiveIndices$RefractiveIndex[materialSamples[2]]
  angle <-sample(10:70,1)
refractedAngle <- rad2deg(asin(sin(material1refractiveIndex*deg2rad(angle)/material2refractiveIndex)))
ray1length <- min(3/cos(deg2rad(angle)),3/cos(deg2rad(90-angle)))
ray2length <- min(3/cos(deg2rad(refractedAngle)),3/cos(deg2rad(90-refractedAngle)))

## Insert the vraibles above into the template
  printstring<-cat(printstring,sprintf(template,material1name,material2name,90+angle,ray1length,90-refractedAngle,ray2length,90+angle,270+refractedAngle,mean(c(90,90+angle)),mean(c(270,270+refractedAngle))),"\\newline ",i,")\\newline",sep="")
  
## Loop to build the rows in the table. I hope for a better way to do this.
  if((i/3)%%1==0){
    printstring<-cat(printstring,"\\\\")
  } else{
    printstring<-cat(printstring,"&")
  }

  ## Determine which material has the higher fractive index
  if(as.numeric(material1refractiveIndex)>as.numeric(material2refractiveIndex)){
    answers<-c(answers,material1name)
  } else{
    answers<-c(answers,material2name)
  }
}
cat(printstring,"\\end{tabular}\\end{center}\\clearpage")
```

## Answers

```{r, results = "asis", echo=FALSE}
##Loop through answer table
for (j in 2:length(answers))(
  cat(" ",j-1,") ",answers[j],"\n",sep="")
)
```