---
title: "Images"
output:
  pdf_document: 
    keep_tex: no
    latex_engine: lualatex
    template: ../worksheetTemplate.tex
  html_document: default
subtitle: Reflection
institute: Version f
include-header:
- \def\arraystretch{0.50}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pracma)
```

Determine the position of the image of the star for each diagram below.

```{r, results = "asis", echo=FALSE}
numberOfImages<-12
## Base template for creating a refraction ray diagram, originally found here: http://texample.net/tikz/examples/refraction/
template <- "\\scalebox{0.8}{\\begin{tikzpicture}\\begin{scope}[rotate=%s]

    %% define coordinates
    \\coordinate (O) at (0,0) ;
    \\coordinate (S) at (%s,%s) ;
    \\coordinate (R1) at (%s,0) ;
    \\coordinate (R2) at (%s,0) ;
    \\coordinate (I) at (%s,%s) ;
    \\draw node[fill,star] at (S) {};

    %% media
    %%\\fill[white!25!,opacity=.3] (-3.6,0) rectangle (3.6,3.6);
    \\fill[white!25!] (-3.6,0) rectangle (3.6,-3.6);

    %% rays
    %% \\draw[red, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{<}}}}] (R1) -- (S) ;
    %% \\draw[red, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{<}}}}] (R2) -- (S) ;
    \\draw[black,line width=.5pt,postaction={draw,decorate,decoration={border,angle=-45,amplitude=0.3cm,segment length=2mm}}](-4,0)--(4,0);

    %% axis
    %% \\draw[dash pattern=on5pt off3pt] (R1) -- (%s,%s);
    %% \\draw[dash pattern=on5pt off3pt] (R2) -- (%s,%s);

    %% \\draw[blue, ultra thick,dash pattern=on5pt off3pt] (R1) -- (I) ;
    %% \\draw[blue, ultra thick,dash pattern=on5pt off3pt] (R2) -- (I) ;

    %% \\draw[blue, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{>}}}}] (R1) -- +(%s:1cm) ;
    %% \\draw[blue, ultra thick, postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{>}}}}] (R2) -- +(%s:1cm) ;
    %% \\draw node[fill,star] at (I) {};
    \\end{scope}\\end{tikzpicture}}"

## Loop to create each example
areflectxs<-data.frame()
aobjectx<-array()
aobjecty<-array()
atwist<-array()
printstring<-" "
for (i in 1:numberOfImages) {
  reflectxs <- sample(-3.5:3.5,3,replace=FALSE)
  objectx <- reflectxs[3]
  objecty <- sample(1.0:3.1,1)
  twist <- sample(c(-30:30,150:210),1)
  reflectangle1<-rad2deg(atan(objecty/abs(reflectxs[1]-objectx)))
  reflectangle2<-rad2deg(atan(objecty/abs(reflectxs[2]-objectx)))
  
## Insert the vraibles above into the template
  plotstring<-paste(i,")\\newline",sprintf(template,twist,objectx,objecty,reflectxs[1],reflectxs[2],objectx,-objecty,reflectxs[1],objecty,reflectxs[2],objecty,if(reflectxs[1]<=objectx){180-reflectangle1}else{reflectangle1},if(reflectxs[2]<=objectx){180-reflectangle2}else{reflectangle2}),"\\newline",sep="")
  
## Loop to build the rows in the table. I hope for a better way to do this.
  if(i %% 2 == 0){
printstring<-paste(printstring,plotstring,"\\end{tabular}\\end{center}")
  } else{
        printstring<-paste(printstring,"\\begin{center}\\begin{tabular}{p{8cm} p{8cm}}",plotstring," & ")
  }

areflectxs<-rbind(areflectxs,reflectxs)
aobjectx<-c(aobjectx,objectx)
aobjecty<-c(aobjecty,objecty)
atwist<-c(atwist,twist)  
}
cat(printstring,"\\clearpage")
```

## Answers

These answers represent only one possible ray diagram for coming to your answer. Your answer should contain all the same elements.

```{r, results = "asis", echo=FALSE}

## Base template for creating a refraction ray diagram, originally found here: http://texample.net/tikz/examples/refraction/
template <- "\\scalebox{0.8}{\\begin{tikzpicture}\\begin{scope}[rotate=%s]

    %% define coordinates
    \\coordinate (O) at (0,0) ;
    \\coordinate (S) at (%s,%s) ;
    \\coordinate (R1) at (%s,0) ;
    \\coordinate (R2) at (%s,0) ;
    \\coordinate (I) at (%s,%s) ;
    
    \\draw node[fill,star] at (S) {};

    %% media
    %%\\fill[white!25!,opacity=.3] (-3.6,0) rectangle (3.6,3.6);
    \\fill[white!25!] (-3.6,0) rectangle (3.6,-3.6);

    %% rays
    \\draw[red, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{<}}}}] (R1) -- (S) ;
    \\draw[red, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{<}}}}] (R2) -- (S) ;
  \\draw[black,line width=.5pt,postaction={draw,decorate,decoration={border,angle=-45,
                    amplitude=0.3cm,segment length=2mm}}](-4,0)--(4,0);

    %% axis
    \\draw[dash pattern=on5pt off3pt] (R1) -- (%s,%s);
    \\draw[dash pattern=on5pt off3pt] (R2) -- (%s,%s);

    \\draw[blue, ultra thick,dash pattern=on5pt off3pt] (R1) -- (I) ;
    \\draw[blue, ultra thick,dash pattern=on5pt off3pt] (R2) -- (I) ;

    \\draw[blue, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{>}}}}] (R1) -- +(%s:1cm) ;

    \\draw[blue, ultra thick, postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{>}}}}] (R2) -- +(%s:1cm) ;



    \\draw node[fill,star] at (I) {};
\\end{scope}
\\end{tikzpicture}}"


printstring<-""
for (i in 1:numberOfImages) {
  reflectxs <- as.numeric(areflectxs[i,])
  objectx <- aobjectx[i+1]
  objecty <- aobjecty[i+1]
  reflectangle1<-rad2deg(atan(objecty/abs(reflectxs[1]-objectx)))
  reflectangle2<-rad2deg(atan(objecty/abs(reflectxs[2]-objectx)))
  
## Insert the vraibles above into the template
  plotstring<-paste(i,")\\newline",sprintf(template,twist,objectx,objecty,reflectxs[1],reflectxs[2],objectx,-objecty,reflectxs[1],objecty,reflectxs[2],objecty,if(reflectxs[1]<=objectx){180-reflectangle1}else{reflectangle1},if(reflectxs[2]<=objectx){180-reflectangle2}else{reflectangle2}),"\\newline",sep="")
  
## Loop to build the rows in the table. I hope for a better way to do this.
  if(i %% 2 == 0){
printstring<-paste(printstring,plotstring,"\\end{tabular}\\end{center}")
  } else{
        printstring<-paste(printstring,"\\begin{center}\\begin{tabular}{p{8cm} p{8cm}}",plotstring," & ")
  }

  
}
cat(printstring,"\\clearpage")

```