---
title: "Law of Reflection"
output:
  pdf_document: 
    keep_tex: no
    latex_engine: lualatex
    template: ../worksheetTemplate.tex
  html_document: default
subtitle: Reflection
institute: Version a
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pracma)
```

For each of the following ray diagrams measure the angle of incidence, $i$ and reflection $r$.

```{r, results = "asis", echo=FALSE}

## Base template for creating a refraction ray diagram, originally found here: http://texample.net/tikz/examples/refraction/
template <- "\\scalebox{0.8}{\\begin{tikzpicture}

    %% define coordinates
    \\coordinate (O) at (0,0) ;
    \\coordinate (A) at (0,3) ;
    
    %% media
    \\fill[blue!25!,opacity=.3] (-3,0) rectangle (3,3);

    %% rays
    \\draw[red, ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{<}}}}] (O) -- (%s:%s);
    \\draw[blue,ultra thick,postaction={decorate,decoration={markings,mark=at position .65 with {\\arrow[scale=1,>=stealth]{>}}}}] (O) -- (%s:%s);
  \\draw[black,line width=.5pt,postaction={draw,decorate,decoration={border,angle=-45,
                    amplitude=0.3cm,segment length=2mm}}](-3,0)--(3,0);

    %% axis
    \\draw[dash pattern=on5pt off3pt] (O) -- (A);

    %% angles
    \\draw (0,1) arc (90:%s:1);
    \\draw (0,1.2) arc (90:%s:1.2) ;
    \\node[] at (%s:1.4)  {$\\theta_{1}$};
    \\node[] at (%s:1.6)  {$\\theta_{2}$};
\\end{tikzpicture}}"

printstring<-"\\begin{center}\\begin{tabular}{ p{5cm} p{5cm} p{5cm} }"
answers<-array()

## Loop to create each example
for (i in 1:18) {
  angle <-sample(10:89,1)
rayLength <- min(3/cos(deg2rad(angle)),3/cos(deg2rad(90-angle)))

## Insert the vraibles above into the template
  printstring<-cat(printstring,sprintf(template,90+angle,rayLength,90-angle,rayLength,90+angle,90-angle,mean(c(90,90+angle)),mean(c(90-angle,90))),"\\newline ",i,")\\newline",sep="")
  
## Loop to build the rows in the table. I hope for a better way to do this.
  if((i/3)%%1==0){
    printstring<-cat(printstring,"\\\\")
  } else{
    printstring<-cat(printstring,"&")
  }

  ## Add answer to answers array
    answers<-c(answers,angle)
}
cat(printstring,"\\end{tabular}\\end{center}\\clearpage")
```

## Answers

```{r, results = "asis", echo=FALSE}
##Loop through answer table
for (j in 2:length(answers))(
    cat(j-1,") $i$=", answers[j],"\\degree \\, $r$=",answers[j],"\\degree \n",sep="")
)
```